knp_gaufrette:
    adapters:
        local_storage:
            local:
                directory: "%kernel.project_dir%/var/storage"

    filesystems:
        my_storage:
            adapter: local_storage
