services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Spinbits\SyliusGoogleAnalytics4Plugin\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Kernel.php'

    sylius.google_tag_manager.block_event_listener.layout.before_head:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'head.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.head, method: onBlockEvent }

    sylius.google_tag_manager.block_event_listener.layout.before_body:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'body.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.before_body, method: onBlockEvent }

    sylius.google_tag_manager.block_event_listener.layout.after_body:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'after_body.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.after_body, method: onBlockEvent }

    Spinbits\SyliusGoogleAnalytics4Plugin\Factory\ItemFactory:
        arguments:
            $productVariantResolver: '@sylius.product_variant_resolver.default'
            
                
    Spinbits\SyliusGoogleAnalytics4Plugin\Storage\SessionFactoryWithEventsBag:
        decorates: session.factory
        arguments: ['@.inner']
